# Generated by Django 4.2.20 on 2025-04-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transection_id',
            new_name='transaction_id',
        ),
    ]
