# Generated by Django 4.2.20 on 2025-05-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
