# Generated by Django 4.2.20 on 2025-05-01 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_categoryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
