# Generated by Django 4.2.20 on 2025-05-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_categoryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
