# Generated by Django 4.2.20 on 2025-05-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
