# Generated by Django 4.2.20 on 2025-05-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_product_discount_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_end',
        ),
    ]
